### ISSUE TITLE
functional_storage in consent mode

### ISSUE THREAD

**Issue by sergiomartinezdecestafe** [Ayudante/gtm-consent-state#1]
Hi,

In your template code it seems that you are trying to read "functional_storage" when apparently following Google's Tag Manager documentation it should be "functionality_storage".

https://support.google.com/tagmanager/answer/10718549?hl=en

I've had to add a read permission in order to be able to read this consent, however that means that I'm no longer subscribed to changes you could make on the template.

Regards,

Sergio

**Comment by AndersBolander** [comment]
It is a cool template, but it needs Sergio's fix. Same problem here. I adjusted the code and it works. 

Best 
Anders

**Comment by alxbenjamin** [comment]
Same issue here, Can you please fix this. Thank you very much

**Comment by giovaniortolani** [comment]
Hi, @alxbenjamin @AndersBolander @sergiomartinezdecestafe. I opened a PR adding these 2 new parameters (`ad_user_data`and `ad_personalization`) and fixing this typo in `functionality_storage`.

https://github.com/Ayudante/gtm-consent-state/pull/4.

If you want you can download it from my repository.
https://github.com/giovaniortolani/gtm-consent-state

**Comment by DaisakuHataoka** [comment]
Everyone

I'm sorry it took me so long to notice this, even though you pointed it out to me!
And giovaniortolani, thanks for the pull request for the corrected version!
