### ISSUE TITLE
Google Constent Mode 2 new tags

### ISSUE THREAD

**Issue by 01Kuzma** [Ayudante/gtm-consent-state#2]
Hi,
template needs a simple update, it lacks two new parameters:
   
_ad_user_data_
_ad_personalization_

**Comment by giovaniortolani** [comment]
Hi, @01Kuzma. I opened a PR adding these 2 parameters.

https://github.com/Ayudante/gtm-consent-state/pull/4.

If you want you can download it from my repository.
https://github.com/giovaniortolani/gtm-consent-state

**Comment by DaisakuHataoka** [comment]
Hi, 01Kuzma and giovaniortolani.

Thank you very much!
Pull requests have been merged.
